dist: xenial
language: python
addons:
  apt: 
    packages:
      - libmysqlclient-dev

python:
  - "2.7"
  - "3.7"

matrix:
  allow_failures:
    - python: "3.7"

before_script:
  - pip install flake8
  # TODO: Fix the remaining tests and remove --exit-zero
  - flake8 . --count --exit-zero --select=E9,F63,F72,F82 --show-source --statistics

install:
  - pip install .

script: gryphon-runtests
