dist: xenial
language: python
addons:
  apt: 
    packages:
      - libmysqlclient-dev

python:
  - "2.7"

install:
  - pip install .

before_script:
  - pip install flake8
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

script: gryphon-runtests
