#!/bin/bash

my_dir="$(dirname "$0")"
source "$my_dir/.env"

/usr/bin/screen -p emerald -S emerald -X stuff "$\003\nforeman start\n"
curl -X POST --data-urlencode 'payload={"channel": "#notifications", "username": "emerald-havoc", "text": "Restarted due to heartbeat failure", "icon_emoji": ":arrows_counterclockwise:"}' $SLACK_WEBHOOK_URL